# Config with testing paths for PMM trajectory generation

waypoints:
  [ 
    [0, 0, 0], # Start position
    [15, -15, 0],
    [20, 0, 0],
    [15, 15, 0],
    [0, 0, 0],
    [-15, -15, 0],
    [-20, 0, 0],
    [-15, 15, 0],
    [0, 0, 0] # End position
  ]

start_velocity : [0, 0, 0]
end_velocity : [0, 0, 0]
