# Config with testing paths for PMM trajectory generation

waypoints:
  [ 
    [1, 1, 0],
    [-1, 1, 0],
    [-1, -1, 0],
    [1, -1, 0],
  ]
start:
  position: [2, 1, 0]
  velocity: [0, 0, 0]

end:
  position: [2, -1, 0]
  velocity: [0, 0, 0]
