# Config with testing paths for PMM trajectory generation

waypoints:
  [ 
    [2, 1, 0],
    [1, 1, 0],
    [-1, 1, 0],
    [-1, -1, 0],
    [1, -1, 0],
    [2, -1, 0],
  ]
start_velocity: [0, 0, 0]

end_velocity: [0, 0, 0]
