# Config with testing paths for PMM trajectory generation

start_velocity: [0 , 0 , 0]
end_velocity: [0 , 0 , 0]
waypoints: [
      [ -5.0,4.5,1.2],
      [ -0.90 , -1.27 , 3.48 ],
      [ 9.09 , 6.26 , 1.08 ],
      [ 9.27 , -3.46 , 1.17 ],
      [ -4.0 , -6.25 , 3.40 ],
      [ -4.48 , -5.94 , 1.05 ],
      [ 4.45 , -0.80 , 1.09 ],
      [ -2.65 , 6.51 , 1.30 ],
      [ -0.90 , -1.27 , 3.48 ],
      [ 9.09 , 6.26 , 1.08 ],
      [ 9.27 , -3.46 , 1.17 ],
      [ -4.0 , -6.25 , 3.40 ],
      [ -4.48 , -5.94 , 1.05 ],
      [ 4.45 , -0.80 , 1.09 ],
      [ -2.65 , 6.51 , 1.30 ],
      [ -0.90 , -1.27 , 3.48 ],
      [ 9.09 , 6.26 , 1.08 ],
      [ 9.27 , -3.46 , 1.17 ],
      [ -2.5, -6.0, 4.0 ]]
