# Config with testing paths for PMM trajectory generation

waypoints: [[0,0,0],[4,4,0],[-4,8,0],[4,12,0],[-4,16,0],[4,20,0],[0,26,4],[-4,20,0],[4,16,0],[-4,12,0],[4,8,0],[-4,4,0],[0,0,0]]

start_velocity: [0 , 0 , 0]
end_velocity: [0 , 0 , 0]
